name: Build and Deploy MkDocs

on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-pyscript
          pip install mkdocs-jupyter


      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-pages --force